routes/web.php
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */
Route::get('clear-cache', function () {
    $exitCode = Artisan::call('config:clear');
    return back();
})->name('clear-cache');
/***********************  UI Routes *********************/
Route::get('/upload-video', 'UIController@upload_video');
Route::get('/video-notification', 'UIController@video_notification');
/***********************  UI Routes *********************/
/*********************** TEST ROUTES *********************/
Route::get('/test', 'SampleController@test');
Route::post('/test', 'SampleController@get_image')->name('sample');
Route::get('/export', 'SampleController@sample_export');
Route::get('/compress', 'SampleController@compress_image_upload')->name('compress.image');
Route::get('/compress/i', 'SampleController@compress_image_check');
Route::post('/compress/image', 'SampleController@getImageThumbnail');
Route::get('/sendpush', 'SampleController@send_push_notification');
/*********************** TEST ROUTES *********************/
// Route::get('/upload' , 'ApplicationController@subscriptions')->name('subscriptions.index');
Route::get('/generate/index', 'ApplicationController@generate_index');
/***********************  UI Routes *********************/
Route::get('/upload-video', 'AdminController@upload_video');
// Singout from all devices which is expired account
Route::get('signout/all/devices', 'ApplicationController@signout_all_devices');
Route::get('/email/verification', 'ApplicationController@email_verify')->name('email.verify');
Route::get('/check/token', 'ApplicationController@check_token_expiry')->name('check_token_expiry');
// Installation
Route::get('/configuration', 'InstallationController@install')->name('installTheme');
Route::get('/system/check', 'InstallationController@system_check_process')->name('system-check');
Route::post('/configuration', 'InstallationController@theme_check_process')->name('install.theme');
Route::post('/install/settings', 'InstallationController@settings_process')->name('install.settings');
// CRON
Route::get('/publish/video', 'ApplicationController@cron_publish_video')->name('publish');
Route::get('/notification/payment', 'ApplicationController@send_notification_user_payment')->name('notification.user.payment');
Route::get('/payment/expiry', 'ApplicationController@user_payment_expiry')->name('user.payment.expiry');
Route::get('/payment/failure', 'ApplicationController@payment_failure')->name('payment.failure');
Route::get('/automatic/renewal', 'ApplicationController@automatic_renewal_stripe')->name('automatic.renewal');
// Generral configuration routes
Route::post('project/configurations', 'ApplicationController@configuration_site');

// Static Pages
//Route::get('/privacy', 'UserApiController@privacy')->name('user.privacy');
//Route::get('/terms_condition', 'UserApiController@terms')->name('user.terms');
//Route::get('/static/terms', 'UserApiController@terms')->name('user.terms');
Route::get('/contact', 'UserController@contact')->name('user.contact');
//Route::get('/privacy_policy', 'ApplicationController@privacy')->name('user.privacy_policy');
//Route::get('/terms', 'ApplicationController@terms')->name('user.terms-condition');
//Route::get('/about', 'ApplicationController@about')->name('user.about');

// Video upload
Route::post('select/sub_category', 'ApplicationController@select_sub_category')->name('select.sub_category');
Route::post('select/genre', 'ApplicationController@select_genre')->name('select.genre');
Route::get('/admin-control', 'ApplicationController@admin_control')->name('admin_control');
Route::post('save_admin_control', 'ApplicationController@save_admin_control')->name('save_admin_control');
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('login', 'Auth\AdminAuthController@showLoginForm')->name('login');
    Route::post('login', 'Auth\AdminAuthController@login')->name('login.post');
    Route::get('logout', 'Auth\AdminAuthController@logout')->name('logout');
    // Registration Routes...
    Route::get('register', 'Auth\AdminAuthController@showRegistrationForm');
    Route::post('register', 'Auth\AdminAuthController@register');
    // Channels routes
    Route::get('channels', 'AdminController@channels')->name('channels');
    Route::get('channel/add', 'AdminController@add_channel');
    Route::get('channel/edit/{id}', 'AdminController@edit_channel');
    Route::get('channel/{id}', 'AdminController@edit_channel');
    Route::post('channel/save', 'AdminController@save_channel');
    Route::get('channel/delete/{id}', 'AdminController@delete_channel');
    // Password Reset Routes...
    Route::get('password/reset', 'Auth\AdminPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\AdminPasswordController@sendResetLinkEmail');
    Route::get('password/reset/{token?}', 'Auth\AdminPasswordController@showResetForm');
    Route::post('password/reset', 'Auth\AdminPasswordController@resetPassword');
    Route::get('/', 'AdminController@dashboard')->name('dashboard');
    Route::get('/profile', 'AdminController@profile')->name('profile');
    Route::post('/profile/save', 'AdminController@profile_save')->name('save.profile');
    Route::post('/change/password', 'AdminController@change_password')->name('change.password');
    // users
    Route::get('/users', 'AdminController@users')->name('users');
    Route::get('users/create', 'AdminController@users_create')->name('users.create');
    Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');
    Route::post('users/create', 'AdminController@users_save')->name('save.user');
    Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');
    Route::get('/users/view/{id}', 'AdminController@users_view')->name('users.view');
    Route::get('/users/subprofiles/{id}', 'AdminController@users_sub_profiles')->name('users.subprofiles');
    Route::get('/users/password_reset/{id}', 'AdminController@users_password_reset')->name('users.password_reset');
    Route::post('/users/password_update', 'AdminController@users_password_update')->name('users.password_update');
    Route::get('users/status/change', 'AdminController@users_status_change')->name('users.status.change');
    // Users Model Login
    Route::post('/user/login/create', 'Auth\UserLoginController@login')->name('login.save');

    // Route::post('/user/forget/password','Auth\UserRegistrationController@forget_password')->name('forget.password');
    // Users Model Login
    Route::get('/users/upgrade/{id}', 'AdminController@users_upgrade')->name('users.upgrade');
    Route::any('users/upgrade-disable', 'AdminController@users_upgrade_disable')->name('users.upgrade.disable');
    Route::get('moderators/redeems/{id?}', 'AdminController@moderators_redeem_requests')->name('moderators.redeems');
    Route::any('/moderators/payout/invoice', 'AdminController@moderators_redeems_payout_invoice')->name('moderators.payout.invoice');
    Route::post('moderators/payout/direct', 'AdminController@moderators_redeems_payout_direct')->name('moderators.payout.direct');
    Route::any('/moderators/payout/response', 'AdminController@moderators_redeems_payout_response')->name('moderators.payout.response');
    Route::get('/users/verify/{id?}', 'AdminController@users_verify_status')->name('users.verify');
    Route::get('/user/clear-login', 'AdminController@clear_login')->name('users.clear-login');
    // User History - admin
    Route::get('/user/history/{id}', 'AdminController@view_history')->name('user.history');
    Route::get('/delete/history/{id}', 'AdminController@delete_history')->name('delete.history');
    // User Wishlist - admin
    Route::get('/user/wishlist/{id}', 'AdminController@view_wishlist')->name('user.wishlist');
    Route::get('/delete/wishlist/{id}', 'AdminController@delete_wishlist')->name('delete.wishlist');
    // Spam Videos
    Route::get('/spam-videos', 'AdminController@spam_videos')->name('spam-videos');
    Route::get('/spam-videos/user-reports/{id}', 'AdminController@spam_videos_user_reports')->name('spam-videos.user-reports');
    // Redeem Pay from Paypal
    Route::get('moderator/redeem-pay', 'RedeemPaymentController@redeem_pay')->name('moderator.redeem_pay');
    Route::get('moderator/redeem-pay-status', 'RedeemPaymentController@redeem_pay_status')->name('moderator.redeem_pay_status');
    // Moderators
    Route::get('/moderators', 'AdminController@moderators')->name('moderators');
    Route::get('/add/moderator', 'AdminController@add_moderator')->name('add.moderator');
    Route::get('/edit/moderator/{id}', 'AdminController@edit_moderator')->name('edit.moderator');
    Route::post('/add/moderator', 'AdminController@add_moderator_process')->name('save.moderator');
    Route::get('/delete/moderator/{id}', 'AdminController@delete_moderator')->name('delete.moderator');
    Route::get('/moderator/approve/{id}', 'AdminController@moderator_approve')->name('moderator.approve');
    Route::get('/moderator/decline/{id}', 'AdminController@moderator_decline')->name('moderator.decline');
    Route::get('/view/moderator/{id}', 'AdminController@moderator_view_details')->name('moderator.view');
    // Sub Admins
    Route::get('/subadmins', 'AdminController@subadmins')->name('subadmins')->middleware('subadmin');
    Route::get('/add/subadmin', 'AdminController@add_subadmin')->name('add.subadmin')->middleware('subadmin');
    Route::get('/edit/subadmin/{id}', 'AdminController@edit_subadmin')->name('edit.subadmin')->middleware('subadmin');
    Route::post('/add/subadmin', 'AdminController@add_subadmin_process')->name('save.subadmin')->middleware('subadmin');
    Route::get('/delete/subadmin/{id}', 'AdminController@delete_subadmin')->name('delete.subadmin')->middleware('subadmin');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\Helper;

class Category extends Model
{
	public function subCategory()
    {
        return $this->hasMany('App\SubCategory');
    }

    public function genre()
    {
        return $this->hasMany('App\Genre');
    }

    public function adminVideo()
    {
        return $this->hasMany('App\AdminVideo');
    }

	public static function boot()
    {
        //execute the parent's boot method 
        parent::boot();

        //delete your related models here, for example
        static::deleting(function($categories)
        {
            foreach($categories->subCategory as $sub_category)
            {  

                foreach($sub_category->subCategoryImage as $image) {

                    Helper::delete_picture($image->picture,'/uploads/images/');  

                    $image->delete();
                } 

                $sub_category->delete();
            } 

            foreach($categories->adminVideo as $video)
            {           

                deleteVideoAndImages($video);

                $video->delete();
            } 

            foreach($categories->genre as $genre)
            {                

                Helper::delete_picture($genre->image,'/uploads/images/');

                
                if ($genre->video) {

                    Helper::delete_picture($genre->video, '/uploads/videos/original/');   

                }

                if ($genre->subtitle) {
                    
                    Helper::delete_picture($genre->subtitle, "/uploads/subtitles/");

                }  
  

                $genre->delete();
            } 

        });	

    }

    
}

resources/views/admin/categories/add-category.blade.php
@extends('layouts.admin')

@section('title', tr('add_category'))

@section('content-header', tr('add_category'))

@section('breadcrumb')
    <!-- <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.categories')}}"><i class="fa fa-suitcase"></i> {{tr('categories')}}</a></li>
    <li class="active">{{tr('add_category')}}</li> -->
@endsection

@section('styles')

    <link rel="stylesheet" href="{{asset('admin-css/plugins/iCheck/all.css')}}">

@endsection

@section('content')

@include('notification.notify')


<div class="main-content">
    <form class="form-horizontal" action="{{route('admin.save.category')}}" method="POST" enctype="multipart/form-data" role="form">
        <div class="row">
            <div class="col-md-8">
                <div class="boxx">
                    <div class="box-bodyy">
                        <div class="card mb-20">
                            <div class="card-header">
                                <label for="title">{{tr('add_category')}}</label>
                            </div>
                            <div class="card-body">
                                <div class="form-body">

                                    <div class="form-group">
                                        <label for="name">{{tr('name')}}*</label>
                                        <input type="text" required class="form-control" pattern = "[a-zA-Z0-9\s\-\.]{2,100}" title="{{tr('only_alphanumeric')}}" id="name" name="name" placeholder="{{tr('category_name')}}">
                                    </div>
                                    <div class="form-group">
                                        <label for="description">{{tr('description')}}*</label>
                                        <textarea required class="form-control" id="ckeditor" name="description" placeholder="{{tr('description')}}" value="{{old('description')}}"></textarea>
                                    </div>
                                    <div class="form-group">
                                        <div class="checkbox checklab">
                                            <label></label>
                                            <label>
                                                <input type="checkbox" name="is_series" value="1" class="minimal-red"> {{tr('is_series')}}
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @seoForm($category)
                    </div>
                </div>
            </div>
            <div class="col-md-4">

                <div class="card mb-20">
                    <div class="card-header">
                        <label for="">Publish</label>
                    </div>
                    <div class="card-body">
                        <div class="publish_card">
                        {!! App\Helpers\Helper::published_block($category) !!}

                        
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="publish_item">
                            <div class="box-tools pull-left" style="width: 30%">
                                <!-- <a href="" class="btn btn-danger">{{tr('cancel')}}</a> -->
                                @if(Setting::get('admin_delete_control'))
                                    <a href="#" class="btn btn-primary" disabled>Publish</a>
                                @else
                                    <button type="submit" class="btn btn-primary">Publish</button>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card mb-20">
                    <div class="card-header">
                        <label for="">Upload Image</label>
                    </div>
                    <div class="card-body">
                        <div class="image-upload">
                            <div class="image-upload-item">
                                <label for="picture">{{tr('picture')}}</label> 
                                <input style="display:none" type="file" required accept="image/jpeg,image/png" id="picture" name="picture" placeholder="{{tr('picture')}}" onchange="loadFile(this,'image_preview')">
                                @if($category->picture)
                                    <img src="{{$category->picture}}" onclick="$('#picture').click();return false;" id="image_preview" style="width: 100%; height: auto; margin-bottom: 0px; display: block; margin: 0 auto">
                                @else
                                    <img src="{{url('images/default.png')}}" onclick="$('#picture').click();return false;" id="image_preview" style="width: 100%; height: auto; margin-bottom: 0px; display: block; margin: 0 auto">
                                @endif
                                <p class="help-block">{{tr('image_validate')}} {{tr('image_square')}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            
            </div>
        </div>
    </form>

</div>

@endsection

@section('scripts')

   <script src="{{asset('admin-css/plugins/iCheck/icheck.min.js')}}"></script>

    <script type="text/javascript">

        function loadFile(event,id){

            $('#'+id).show();

            var reader = new FileReader();

            reader.onload = function(){

                var output = document.getElementById(id);

                output.src = reader.result;
            };

            reader.readAsDataURL(event.files[0]);
        }

        $(document).ready(function() {
            $(document).on('keyup', '#name', function(){
                var heading = $(this).val();
                $('#page_title').val(heading);
                $('input[name="meta[5]"]').val(heading);
                $('input[name="meta[26]"]').val(heading);
            });
        });
    </script>

@endsection

resources/views/admin/categories/categories.blade.php
@extends('layouts.admin')

@section('title', tr('categories'))

@section('content-header', tr('categories'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li class="active"><i class="fa fa-suitcase"></i> {{tr('categories')}}</li>
@endsection

@section('content')

	@include('notification.notify')

	<div class="row">
        <div class="col-lg-12">
          	<div class="box box-primary">
	          	<div class="box-header label-primary">
	                <b style="font-size:18px;">{{tr('categories')}}</b>
	                <a href="{{route('admin.add.category')}}" class="btn btn-default pull-right">{{tr('add_category')}}</a>
	            </div>
	            
	            <div class="box-body">

	            	@if(count($categories) > 0)

		              	<table id="datatable-withoutpagination" class="table table-bordered table-striped">

							<thead>
							    <tr>
							      {{-- <th>{{tr('id')}}</th> --}}
							      <th>{{tr('category')}}</th>
							      <th>{{tr('picture')}}</th>
							      <th>{{tr('sub_categories')}}</th>
							      <th>{{tr('is_series')}}</th>
							      <th>{{tr('status')}}</th>							      
							    </tr>
							</thead>

							<tbody>
								@foreach($categories as $i => $category)

								    <tr>
								      	{{-- <td>{{showEntries($_GET, $i+1)}}</td> --}}
								      	<td>{{$category->name}}

								      		<ul class="table-row-actions"> 
	            								
						                  	<li role="presentation">
                                                @if(Setting::get('admin_delete_control'))
                                                    <a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{tr('edit')}}</a>
                                                @else
                                                    <a role="menuitem" tabindex="-1" href="{{route('admin.edit.category' , array('id' => $category->id))}}">{{tr('edit')}}</a>
                                                @endif
                                            </li>
                                            
						                  	<li role="presentation">

							                  	@if(Setting::get('admin_delete_control'))

								                  	<a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{tr('delete')}}</a>

								                @else

						                  			<a role="menuitem" tabindex="-1" onclick="return confirm(&quot;{{tr('category_delete_confirmation' , $category->name)}}&quot;);" href="{{route('admin.delete.category' , array('category_id' => $category->id))}}">{{tr('delete')}}</a>
						                  		@endif
						                  	</li>
											

						                  	@if($category->is_approved)
						                  		<li role="presentation"><a role="menuitem" tabindex="-1" onclick="return confirm(&quot;{{tr('category_decline_confirmation' , $category->name)}}&quot;);" href="{{route('admin.category.approve' , array('id' => $category->id , 'status' =>0))}}">{{tr('decline')}}</a></li>
						                  	@else
						                  		<li role="presentation"><a role="menuitem" tabindex="-1" onclick="return confirm(&quot;{{tr('category_approve_confirmation' , $category->name)}}&quot;);" href="{{route('admin.category.approve' , array('id' => $category->id , 'status' => 1))}}">{{tr('approve')}}</a></li>
						                  	@endif
						                  	

						                  	<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.add.sub_category' , array('category' => $category->id))}}">{{tr('add_sub_category')}}</a></li>

						                  	<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.sub_categories' , array('category' => $category->id))}}">{{tr('view_sub_categories')}}</a></li>				                  

						                  	<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.videos' , array('category_id' => $category->id))}}">{{tr('videos')}}</a></li>
									              
	            							</ul>
								      	</td>
								      	<td>
		                                	<img style="height: 30px;" src="{{$category->picture}}">
		                            	</td>
		                            	<td>
		                            		<a href="{{route('admin.sub_categories' , array('category' => $category->id))}}">
		                            		{{count($category->subCategory)}}</a>
		                            	</td>
		                            	<td>
								      		@if($category->is_series)
								      			<span class="label label-success">{{tr('yes')}}</span>
								       		@else
								       			<span class="label label-warning">{{tr('no')}}</span>
								       		@endif
								       	</td>

								      <td>
								      		@if($category->is_approved)
								      			<span class="label label-success">{{tr('approved')}}</span>
								       		@else
								       			<span class="label label-warning">{{tr('pending')}}</span>
								       		@endif
								       </td>
								       
								    </tr>
								@endforeach
							</tbody>
						
						</table>

						<div align="right" id="paglink"><?php echo $categories->links(); ?></div>


					@else
						<h3 class="no-result">{{tr('no_result_found')}}</h3>
					@endif
	            
	            </div>

          	</div>
        </div>
    </div>

@endsection

resources/views/admin/categories/edit-category.blade.php
@extends('layouts.admin')

@section('title', tr('edit_category'))

@section('content-header', tr('edit_category'))

@section('breadcrumb')
    <!-- <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.categories')}}"><i class="fa fa-suitcase"></i> {{tr('categories')}}</a></li>
    <li class="active">{{tr('edit_category')}}</li> -->
@endsection


@section('styles')

    <link rel="stylesheet" href="{{asset('admin-css/plugins/iCheck/all.css')}}">

@endsection

@section('content')

@include('notification.notify')

<div class="main-content">
    @if(Setting::get('admin_delete_control'))
    <form class="form-horizontal" role="form">
    @else
    <form class="form-horizontal" action="{{route('admin.save.category')}}" method="POST" enctype="multipart/form-data" role="form">
    @endif
        <div class="row">
            <div class="col-md-8">
                <div class="boxx">
                    <div class="box-bodyy">
                        <div class="card mb-20">
                            <div class="card-header">
                                <label for="title">{{tr('edit_category')}}</label>
                            </div>
                            <div class="card-body">
                                <div class="form-body">
                                    <input type="hidden" name="id" value="{{$category->id}}">
                                    <div class="form-group">
                                        <label for="name">{{tr('name')}}*</label>
                                        <input type="text" required class="form-control"  pattern = "[a-zA-Z0-9\s\-\.]{2,100}" title="{{tr('only_alphanumeric')}}" value="{{$category->name}}" id="name" name="name" placeholder="{{tr('enter')}} {{tr('category')}}">
                                    </div>
                                    <div class="form-group">
                                        <label for="description">{{tr('description')}}*</label>
                                        <textarea required class="form-control" id="ckeditor" name="description" placeholder="{{tr('description')}}">{!! $category->description !!}</textarea>
                                    </div>
                                    <div class="form-group">
                                        <div class="checkbox checklab">
                                            <label></label>
                                            <label>
                                                <input type="checkbox" name="is_series" value="1" class="minimal-red" @if($category->is_series) checked @endif> {{tr('is_series')}}
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @seoForm($category)
                    </div>
                </div>
            </div>
            <div class="col-md-4">

                <div class="card mb-20">
                    <div class="card-header">
                        <label for="">Publish</label>
                    </div>
                    <div class="card-body">
                        <div class="publish_card">
                            {!! App\Helpers\Helper::published_block($category) !!}

                            @if($category->id)
                                <div class="publish_item mb-20">
                                    <label>Modified on: <span class="published_on">{{ date('Y-m-d', strtotime($category->updated_at)). ' at '. date('H:i', strtotime($category->updated_at)) }}</span></label>
                                </div>
                            
                            @endif
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="publish_item">
                            <div class="box-tools pull-left" style="width: 30%">
                                <!-- <a href="" class="btn btn-danger">{{tr('cancel')}}</a> -->
                                @if(Setting::get('admin_delete_control'))
                                    <a href="#" class="btn btn-primary" disabled>Update</a>
                                @else
                                    <button type="submit" class="btn btn-primary">Update</button>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card mb-20">
                    <div class="card-header">
                        <label for="">Upload Image</label>
                    </div>
                    <div class="card-body">
                        <div class="image-upload">
                            <div class="image-upload-item">
                                <label for="picture">{{tr('picture')}}</label> 
                                <input style="display:none" type="file" accept="image/png, image/jpeg" id="picture" name="picture" placeholder="{{tr('picture')}}" onchange="loadFile(this,'image_preview')">
                                @if($category->picture)
                                    <img src="{{$category->picture}}" onclick="$('#picture').click();return false;" id="image_preview" style="width: 100%; height: auto; margin-bottom: 0px; display: block; margin: 0 auto">
                                @else
                                    <img src="{{url('images/default.png')}}" onclick="$('#picture').click();return false;" id="image_preview" style="width: 100%; height: auto; margin-bottom: 0px; display: block; margin: 0 auto">
                                @endif
                                <p class="help-block">{{tr('image_validate')}} {{tr('image_square')}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            
            </div>
        </div>
    </form>

</div>

@endsection

@section('scripts')

<script src="{{asset('admin-css/plugins/iCheck/icheck.min.js')}}"></script>

    <script type="text/javascript">

        function loadFile(event,id){

            $('#'+id).show();

            var reader = new FileReader();

            reader.onload = function(){

                var output = document.getElementById(id);

                output.src = reader.result;
            };

            reader.readAsDataURL(event.files[0]);
        }

        $(document).ready(function() {
            $(document).on('keyup', '#name', function(){
                var heading = $(this).val();
                $('#page_title').val(heading);
                $('input[name="meta[5]"]').val(heading);
                $('input[name="meta[26]"]').val(heading);
            });
        });

    </script>
@endsection